package com.team.hairdresser.constant;

public interface AuthorityCodes {
    String VIEW_LOOKUP_VALUE_MANAGEMENT = "VIEW_LOOKUP_VALUE_MANAGEMENT";
    String CREATE_LOOKUP_VALUE = "CREATE_LOOKUP_VALUE";
    String UPDATE_LOOKUP_VALUE = "UPDATE_LOOKUP_VALUE";
    String DELETE_LOOKUP_VALUE = "DELETE_LOOKUP_VALUE";
    String VIEW_USER_MANAGEMENT = "VIEW_USER_MANAGEMENT";
    String UPDATE_AUTHORITY = "UPDATE_AUTHORITY";
    String VIEW_AUTHORITY_MANAGEMENT = "VIEW_AUTHORITY_MANAGEMENT";
    String UPDATE_ROLE_AUTHORITIES = "UPDATE_ROLE_AUTHORITIES";
    String CREATE_ROLE = "CREATE_ROLE";
    String UPDATE_ROLE = "UPDATE_ROLE";
    String DELETE_ROLE = "DELETE_ROLE";
    String VIEW_ROLE_MANAGEMENT = "VIEW_ROLE_MANAGEMENT";
}
